### ISSUE TITLE
Hacktoberfest - Any help is welcome

### ISSUE THREAD

**Issue by rodolfobandeira** [rodolfobandeira/spacex#20]
Any improvement in the project helps. 

- Refactor;
- Add missing endpoints;
- Improve Documentation;
- Improve tests;
- anything helps

**Comment by jude-lawson** [comment]
Hello! 👋 

I have made a PR with a refactor - it's an abstraction on the `retrieve_all` method that is in a handful of resource files. It swaps the method in all of those resources to use a mixed in module method instead. I also noticed the potential for some additional abstractions and if this PR: https://github.com/rodolfobandeira/spacex/pull/43.

I would definitely welcome any feedback and would be happy to make any changes to the PR. Thanks for the opportunity!

**Comment by invacuo** [comment]
@mtking2 Go for it! Please create an issue for this so other hacktoberfesters will know that you are working on it. Thanks!

**Comment by invacuo** [comment]
If you haven't already noticed we already have some of the launch stuff implemented here https://github.com/rodolfobandeira/spacex/blob/master/lib/spacex/launches.rb

**Comment by mtking2** [comment]
@invacuo will do! 👍
