### ISSUE TITLE
Implement Remaining Launches Endpoints

### ISSUE THREAD

**Issue by mtking2** [rodolfobandeira/spacex#47]
The following Launches endpoints are still to be implemented:

- [x] ~[One Launch](https://documenter.getpostman.com/view/2025350/RWaEzAiG#cfcc49e7-5fe4-4dd3-9701-7c5caf7af9fb)~ - #48
- [x] ~[Past Launches](https://documenter.getpostman.com/view/2025350/RWaEzAiG#fce450d6-e064-499a-b88d-34cc22991bcc)~ - #52
- [ ] [Upcoming Launches](https://documenter.getpostman.com/view/2025350/RWaEzAiG#e001c501-9c09-4703-9e29-f91fbbf8db7c)

Reference: https://documenter.getpostman.com/view/2025350/RWaEzAiG#bc65ba60-decf-4289-bb04-4ca9df01b9c1

**Comment by rodolfobandeira** [comment]
Just FIY, the "Upcoming Launches" is already covered by [`SPACEX::Launches.next`](https://github.com/rodolfobandeira/spacex/blob/master/lib/spacex/launches.rb#L12)

**Comment by mtking2** [comment]
Is it? From the API it looks like [`launches/next`](https://documenter.getpostman.com/view/2025350/RWaEzAiG#c75a20cf-50e7-4a4a-8856-ee729e0d3868) returns a singe launch object for just the next scheduled launch. And [`launches/upcoming`](https://documenter.getpostman.com/view/2025350/RWaEzAiG#e001c501-9c09-4703-9e29-f91fbbf8db7c) returns an array of launch objects for all future scheduled launches.

**Comment by rodolfobandeira** [comment]
Facepalming myself. You're totally right.
