### ISSUE TITLE
Implement Payload Endpoint

### ISSUE THREAD

**Issue by maiafernando** [rodolfobandeira/spacex#49]
Reference: https://documenter.getpostman.com/view/2025350/RWaEzAiG#2936485d-1d09-464c-a909-1c2041d67c75

@rodolfobandeira Do you think that it's worth to be implemented? I can do it tonight if you think it's ok to do so.

**Comment by rodolfobandeira** [comment]
@maiafernando For sure, feel free to tackle this!
