### ISSUE TITLE
Implement SpaceX's ships information

### ISSUE THREAD

**Issue by rodolfobandeira** [rodolfobandeira/spacex#5]
Implement "Get All Ships" information endpoint 

Reference: https://documenter.getpostman.com/view/2025350/RWaEzAiG#e520e500-0421-4774-8bcb-8d07b7dfa222

**Comment by benjamin-ross** [comment]
Will do 👍 .  Can you add a `dibs` labels ?

**Comment by rodolfobandeira** [comment]
Hi @benjamin-ross. I'm not sure what do you mean by `dibs` but I switched to `in progress`. That works for you?
Cheers

**Comment by rodolfobandeira** [comment]
@zainalmustofa added his PR into master.

@benjamin-ross If you are still on this, the following improvements are my suggestions:

1. Since the official API doesn't accept indexes (integer), I would implement a method like `SPACEX::Ships.get('AMERICANCHAMPION')` to retrieve a specific ship. This will call: https://api.spacexdata.com/v3/ships/AMERICANCHAMPION

2. `SPACEX::Ships.get` will retrieve all ships. Basically, this will call your `getAll` method. Write tests and document as well.

Cheers!
