### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by rodolfobandeira** [rodolfobandeira/spacex#58]
@maiafernando's PR #57 and @annawinkler's PR #40 were great to clarify the README file. 

I'm creating this issue to discuss better ways so we could improve the README and documentation at all.
Please feel free to share your thoughts and ideas

To start the thread, here is something that worth looking at:
- https://github.com/matiassingers/awesome-readme

**Comment by invacuo** [comment]
That's a pretty good resource to read! I will spend some time on this later tonight.
