### ISSUE TITLE
Implement SpaceX's Dragon capsules information

### ISSUE THREAD

**Issue by rodolfobandeira** [rodolfobandeira/spacex#6]
Returns all dragon capsules information:

Reference: https://documenter.getpostman.com/view/2025350/RWaEzAiG#32f4fc1e-37e8-4d1b-8ec4-ac729441ddb2

**Comment by JackieCalapristi** [comment]
I can take this one! :)

**Comment by JackieCalapristi** [comment]
I've opened a PR for this here: https://github.com/rodolfobandeira/spacex/pull/9
