### ISSUE TITLE
Implement "Launch Pads" endpoint

### ISSUE THREAD

**Issue by rodolfobandeira** [rodolfobandeira/spacex#68]
Reference:

https://docs.spacexdata.com/?version=latest#e232e64a-58a2-4bc0-af42-eb20499425cc

**Comment by fernandomaia** [comment]
Isn't it the same as #66?

**Comment by rodolfobandeira** [comment]
You're right @fernandomaia. My bad, I should be: "Landing Pads". Fixed.

**Comment by invacuo** [comment]
I will take this one
